### ISSUE TITLE
[BUG] - Error message

### ISSUE THREAD

**Issue by DDeAlmeida** [BitCannaGlobal/lunie-ng#21]
When an error raised the Message Pop-Up design didn't change:
- Button to be removed
- Text for Keplr to be removed
Or maybe work on new design for error message

![image](https://user-images.githubusercontent.com/52310650/123840670-e930ef80-d90e-11eb-9cdc-eb5f692ed9ee.png)

**Comment by RaulBernal** [comment]
This looks like a server error at the time
