### ISSUE TITLE
Error code 404 when voting for proposal

### ISSUE THREAD

**Issue by BitCannaGlobal** [BitCannaGlobal/lunie-ng#23]
When trying to vote, error 404 occurred for some users. Inconsistent bug, can't be reproduced by everyone. Seems to affect only some users.

![image_2021_07_01T17_43_44_984Z](https://user-images.githubusercontent.com/39583369/124447021-47335c00-dd81-11eb-86cf-0b677fa64d9f.png)
![image_2021_07_01T17_50_46_569Z](https://user-images.githubusercontent.com/39583369/124447027-48648900-dd81-11eb-8ff9-5cc591002320.png)

**Comment by RaulBernal** [comment]
This looks like a server error at the time
