### ISSUE TITLE
[BUG] - Keplr Connexion

### ISSUE THREAD

**Issue by DDeAlmeida** [BitCannaGlobal/lunie-ng#25]
Open https://testnet-wallet.bitcanna.io/welcome
![image](https://user-images.githubusercontent.com/52310650/124448403-b3628f80-dd82-11eb-8281-18d409f2acd0.png)

Click on "Keplr Browser Extension"
Then a Popup show
![image](https://user-images.githubusercontent.com/52310650/124449175-78149080-dd83-11eb-9373-c63b524a01ba.png)

Close the popup
![image](https://user-images.githubusercontent.com/52310650/124448548-dd1bb680-dd82-11eb-9f78-75b473a23348.png)

Click on "Connect Keplr Extension"
![image](https://user-images.githubusercontent.com/52310650/124449047-59ae9500-dd83-11eb-846b-05751fabb398.png)

**Comment by RaulBernal** [comment]
Outdated, it works ;)
Could be closed
