### ISSUE TITLE
[BUG] - Filter All don't show Jailed or Inactive validator

### ISSUE THREAD

**Issue by DDeAlmeida** [BitCannaGlobal/lunie-ng#6]
In https://testnet-wallet.bitcanna.io/validators, if i select All Validators i hope to see who is inactive or jailed but the filter don't work.
Active = ALL

**Comment by RaulBernal** [comment]
![image](https://user-images.githubusercontent.com/3751926/123599232-acbda080-d7f5-11eb-95a1-12a3cfe169b1.png)

Right

**Comment by BitCannaGlobal** [comment]
Fixed
