### ISSUE TITLE
[BUG] - Validator Jailed not found

### ISSUE THREAD

**Issue by DDeAlmeida** [BitCannaGlobal/lunie-ng#7]
If a validator is jailed for instance : https://seed1.bitcanna.io/validator/bcnavaloper15t72dy6racfdj4qqssrvq6txzl63xednufqvnv
![image](https://user-images.githubusercontent.com/52310650/123420801-4e59ad80-d5bc-11eb-841b-b940cdd018e7.png)

If i try to find the validator in the wallet:
https://testnet-wallet.bitcanna.io/validators/bcnavaloper15t72dy6racfdj4qqssrvq6txzl63xednufqvnv
![image](https://user-images.githubusercontent.com/52310650/123420870-64676e00-d5bc-11eb-85b1-190df38d20e4.png)

**Comment by hellresistor** [comment]
it is because not synced yet.. need bcnad syncs and then unjail.

**Comment by DDeAlmeida** [comment]
> it is because not synced yet.. need bcnad syncs and then unjail.

Mhhh ?
This is not that.

If you search a jailed validator by modify the address. The message "Validator not found" but exist, he is just jailed

**Comment by hellresistor** [comment]
got it.

**Comment by BitCannaGlobal** [comment]
Fixed
